PRAGMA foreign_keys = ON;

UPDATE activities SET catalog_group = 'heliskiing' WHERE slug = 'heli-ski';

INSERT INTO activities (slug, status, name, category, description, card_image_url, hero_image_url, hero_image_alt, price_amount, currency, price_suffix, rating, review_count, catalog_group, skill_level, duration_group, format, sort_order) VALUES
  ('aragveti-ski-tour', 'published', 'Aragveti ski tour', 'Ski touring', 'A full-day guided ski tour in the Gudauri backcountry, selected for the day’s snow, visibility and group experience.', '/assets/activities/freeride-ridge.jpg', '/assets/activities/freeride-ridge.jpg', 'Ski tourer on a snowy ridge near Gudauri', 380, 'GEL', 'per guest', 4.9, 24, 'ski-touring', 'Advanced', 'Full day', 'Guided', 45),
  ('dedaena-ski-tour', 'published', 'Dedaena ski tour', 'Ski touring', 'A sustained ski touring day with a certified guide, a careful pace and terrain chosen around the group and current mountain conditions.', '/assets/activities/gudauri-panorama-riders.jpg', '/assets/activities/gudauri-panorama-riders.jpg', 'Panoramic snowy mountains near Gudauri', 420, 'GEL', 'per guest', 4.9, 18, 'ski-touring', 'Advanced', 'Full day', 'Guided', 46),
  ('miketi-ski-tour', 'published', 'Miketi ski tour', 'Ski touring', 'A guided touring objective for confident skiers who want a quieter route beyond the resort, with a flexible plan for safe conditions.', '/assets/activities/freeride-team-ridge.jpg', '/assets/activities/freeride-team-ridge.jpg', 'Guided ski touring group on a snowy ridge', 420, 'GEL', 'per guest', 4.8, 16, 'ski-touring', 'Advanced', 'Full day', 'Guided', 47);

INSERT INTO activity_tags (activity_id, label, sort_order) VALUES
  ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), '6–7 hours', 0), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Advanced', 1), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Gudauri', 2),
  ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), '7–8 hours', 0), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Advanced', 1), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Gudauri', 2),
  ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), '6–7 hours', 0), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Advanced', 1), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Gudauri', 2);

INSERT INTO activity_facts (activity_id, label, value, sort_order) VALUES
  ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Duration', '6–7 hours', 0), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Level', 'Advanced', 1), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Group', 'Up to 5', 2), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Vertical gain', 'Up to 1,000 m', 3),
  ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Duration', '7–8 hours', 0), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Level', 'Advanced', 1), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Group', 'Up to 5', 2), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Vertical gain', 'Up to 1,200 m', 3),
  ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Duration', '6–7 hours', 0), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Level', 'Advanced', 1), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Group', 'Up to 5', 2), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Vertical gain', 'Up to 1,000 m', 3);

INSERT INTO activity_included (activity_id, label, sort_order) VALUES
  ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Certified mountain guide', 0), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Route planning and avalanche briefing', 1), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Group safety equipment check', 2),
  ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Certified mountain guide', 0), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Route planning and avalanche briefing', 1), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Group safety equipment check', 2),
  ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Certified mountain guide', 0), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Route planning and avalanche briefing', 1), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Group safety equipment check', 2);

INSERT INTO activity_excluded (activity_id, label, sort_order) VALUES
  ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Ski touring equipment rental', 0), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Personal travel insurance', 1),
  ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Ski touring equipment rental', 0), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Personal travel insurance', 1),
  ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Ski touring equipment rental', 0), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Personal travel insurance', 1);

INSERT INTO activity_equipment (activity_id, label, sort_order) VALUES
  ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Touring skis or splitboard with skins', 0), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Avalanche transceiver, probe and shovel', 1), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Helmet, goggles, warm waterproof layers', 2), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'Water, snacks and a small backpack', 3),
  ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Touring skis or splitboard with skins', 0), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Avalanche transceiver, probe and shovel', 1), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Helmet, goggles, warm waterproof layers', 2), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'Water, snacks and a small backpack', 3),
  ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Touring skis or splitboard with skins', 0), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Avalanche transceiver, probe and shovel', 1), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Helmet, goggles, warm waterproof layers', 2), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'Water, snacks and a small backpack', 3);

INSERT INTO activity_schedule (activity_id, time_label, title, description, sort_order) VALUES
  ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), '08:00', 'Meet and safety check', 'Review conditions, equipment and the touring plan.', 0), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), '09:00', 'Ascent and route selection', 'Climb at a sustainable pace with regular condition checks.', 1), ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), '15:30', 'Descent and return', 'Complete the route and debrief with your guide.', 2),
  ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), '08:00', 'Meet and safety check', 'Review conditions, equipment and the touring plan.', 0), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), '09:00', 'Ascent and route selection', 'Climb at a sustainable pace with regular condition checks.', 1), ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), '16:00', 'Descent and return', 'Complete the route and debrief with your guide.', 2),
  ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), '08:00', 'Meet and safety check', 'Review conditions, equipment and the touring plan.', 0), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), '09:00', 'Ascent and route selection', 'Climb at a sustainable pace with regular condition checks.', 1), ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), '15:30', 'Descent and return', 'Complete the route and debrief with your guide.', 2);

INSERT INTO activity_media (activity_id, media_type, url, thumbnail_url, alt, is_featured, sort_order) VALUES
  ((SELECT id FROM activities WHERE slug = 'aragveti-ski-tour'), 'image', '/assets/activities/freeride-ridge.jpg', '/assets/activities/freeride-ridge.jpg', 'Ski tourer on a snowy ridge near Gudauri', 1, 0),
  ((SELECT id FROM activities WHERE slug = 'dedaena-ski-tour'), 'image', '/assets/activities/gudauri-panorama-riders.jpg', '/assets/activities/gudauri-panorama-riders.jpg', 'Panoramic snowy mountains near Gudauri', 1, 0),
  ((SELECT id FROM activities WHERE slug = 'miketi-ski-tour'), 'image', '/assets/activities/freeride-team-ridge.jpg', '/assets/activities/freeride-team-ridge.jpg', 'Guided ski touring group on a snowy ridge', 1, 0);
