import { ActivitySchedule, EquipmentList, IncludedServices, RouteMap as RouteMapBlock, RouteProgram, SafetyRequirements } from '../../design-system';
import { defineComposition } from '../../design-system/architecture/registry';

export default { title: 'Blocks/Detail/Activities', tags: ['autodocs'], parameters: { controls: { disable: true } } };
export const Route = { name: 'Route Program', parameters: { composition: defineComposition({ root: 'RouteProgram' }) }, render: () => <RouteProgram items={[{ title: '10:00 · Meeting', description: 'Equipment and conditions check.' }, { title: '10:30 · Route', description: 'Progressive terrain selection.' }]} /> };
export const Schedule = { name: 'Activity Schedule', parameters: { composition: defineComposition({ root: 'ActivitySchedule' }) }, render: () => <ActivitySchedule description="A clear sequence, so you know what the day looks like before booking." items={[{ time: '10:00', title: 'Meeting point', description: 'Guide briefing and equipment check.' }, { time: '10:30', title: 'Departure', description: 'Start of the route.' }, { time: '12:30', title: 'Mountain lunch break', description: 'A short rest at a scenic point.' }, { time: '14:00', title: 'Return', description: 'Finish at the meeting point.' }]} /> };
export const ScheduleWithLongContent = { name: 'Activity Schedule — Long Content', parameters: { composition: defineComposition({ root: 'ActivitySchedule' }) }, render: () => <ActivitySchedule title="A full day in the mountains" description="A longer content example for checking the route line, text wrapping and localization-ready spacing." items={[{ time: '08:45', title: 'Meet the guide and review the conditions', description: 'We check the forecast, avalanche bulletin, equipment and adapt the route to the experience of the group.' }, { time: '09:30', title: 'Ascent to the starting point', description: 'Transfer and lift access followed by a short approach on foot.' }, { time: '11:00', title: 'Main mountain route', description: 'Several guided descents with pauses to review terrain choices and technique.' }, { time: '15:30', title: 'Return and debrief', description: 'Finish in Gudauri and review the day with your guide.' }]} /> };
export const RouteMap = { name: 'Route Map', parameters: { composition: defineComposition({ root: 'RouteMap' }) }, render: () => <RouteMapBlock start="Kobi lift station" finish="Military Highway" points={[{ title: 'Meeting point', description: 'Equipment and avalanche check.' }, { title: 'Bidara ridge', description: 'Main route start.' }, { title: 'Road exit', description: 'Return transfer pickup.' }]} mapHref="https://maps.google.com" /> };
export const Included = { name: 'Included & Not Included', parameters: { composition: defineComposition({ root: 'IncludedServices' }) }, render: () => <IncludedServices description="Everything covered by the activity and the few things to plan separately." includedItems={[{ title: 'Certified guide', description: 'Local mountain guide for the whole route.' }, 'Safety briefing and equipment check', 'Transfer from the meeting point']} excludedItems={[{ title: 'Personal travel insurance', description: 'Please arrange cover that suits your activity.' }, 'Lunch and personal snacks']} /> };
export const IncludedWithoutExclusions = { name: 'Included — Empty Exclusions', parameters: { composition: defineComposition({ root: 'IncludedServices' }) }, render: () => <IncludedServices includedItems={['Certified guide', 'Safety briefing', 'Transfer from the meeting point']} excludedItems={[]} /> };
export const Equipment = { name: 'What to Bring', parameters: { composition: defineComposition({ root: 'EquipmentList' }) }, render: () => <EquipmentList description="Bring these essentials to stay warm, comfortable and ready for changing mountain weather." items={[{ title: 'Warm waterproof layers', description: 'Jacket, trousers and an insulating mid-layer.' }, { title: 'Helmet and goggles', description: 'A helmet is required for this route.' }, { title: 'Small backpack', description: 'For water, extra layers and personal items.' }, { title: 'Water and snacks', description: 'At least 1 litre of water per person.' }]} note="Avalanche equipment can be provided when it is listed as included." /> };
export const Safety = { name: 'Safety Requirements', parameters: { composition: defineComposition({ root: 'SafetyRequirements' }) }, render: () => <SafetyRequirements notice="Weather can change quickly." items={['Helmet required', 'Follow guide instructions']} /> };
