import type { CompositionParameter, DesignLayer, DesignSystemEntry } from './types';

export const LAYER_DEPENDENCIES: Record<DesignLayer, readonly DesignLayer[]> = {
  primitive: ['primitive'],
  component: ['primitive'],
  block: ['component', 'primitive'],
  pattern: ['block', 'component', 'primitive'],
  template: ['pattern', 'block', 'component', 'primitive']
};

export const DESIGN_SYSTEM_REGISTRY = [
  { id: 'Button', name: 'Button', layer: 'primitive', status: 'stable', storyId: 'primitives-button--playground', sourcePath: 'src/components/UI/Button/Button.jsx', description: 'Semantic action with primary, secondary, ghost, inverse, destructive and link variants.', publicExport: true },
  { id: 'Badge', name: 'Badge', layer: 'primitive', status: 'stable', storyId: 'primitives-badge--playground', sourcePath: 'src/components/UI/Badge/Badge.jsx', description: 'Non-interactive metadata label with semantic tones and controlled media overlay.', publicExport: true },
  { id: 'FilterChip', name: 'Filter Chip', layer: 'primitive', status: 'stable', storyId: 'primitives-filter-chip--playground', sourcePath: 'src/components/UI/FilterChip/FilterChip.jsx', description: 'Interactive filter with default, selected and disabled states.', publicExport: true },
  { id: 'Container', name: 'Container', layer: 'primitive', status: 'stable', storyId: 'primitives-container--playground', sourcePath: 'src/components/UI/Container/Container.jsx', description: 'Responsive wide, detail and article page-width roles with shared margins.', publicExport: true },
  { id: 'Link', name: 'Link', layer: 'primitive', status: 'stable', storyId: 'components-content-and-states--navigation', sourcePath: 'src/components/UI/Core/Core.jsx', description: 'Internal or external semantic link.', publicExport: true },
  { id: 'Icon', name: 'Icon', layer: 'primitive', status: 'beta', storyId: 'components-content-and-states--navigation', sourcePath: 'src/components/UI/Core/Core.jsx', description: 'Accessible icon frame with semantic sizes.', publicExport: true },
  { id: 'Divider', name: 'Divider', layer: 'primitive', status: 'stable', storyId: 'components-content-and-states--surfaces-and-notices', sourcePath: 'src/components/UI/Core/Core.jsx', description: 'Semantic horizontal or vertical separator.', publicExport: true },
  { id: 'Surface', name: 'Surface', layer: 'primitive', status: 'stable', storyId: 'components-content-and-states--surfaces-and-notices', sourcePath: 'src/components/UI/Core/Core.jsx', description: 'Tokenized card, raised, subtle or inverse surface.', publicExport: true },
  { id: 'Skeleton', name: 'Skeleton', layer: 'primitive', status: 'stable', storyId: 'components-content-and-states--async-states', sourcePath: 'src/components/UI/Core/Core.jsx', description: 'Reduced-motion aware loading placeholder.', publicExport: true },

  { id: 'SectionHeading', name: 'Section Heading', layer: 'component', status: 'stable', storyId: 'components-section-heading--playground', sourcePath: 'src/components/UI/SectionHeading/SectionHeading.jsx', description: 'Kicker, required title, optional description and actions across display, section and subsection scales.', publicExport: true },
  { id: 'Accordion', name: 'Accordion', layer: 'component', status: 'stable', storyId: 'components-accordion--default', sourcePath: 'src/components/UI/Accordion/Accordion.jsx', description: 'Keyboard-accessible disclosure group with large transparent rounded rows, prominent questions and trailing state icon.', children: ['AccordionItem'], publicExport: true },
  { id: 'AccordionItem', name: 'Accordion Item', layer: 'primitive', status: 'stable', storyId: 'components-accordion--item', sourcePath: 'src/components/UI/Accordion/Accordion.jsx', description: 'Single labelled disclosure row with touch-safe trigger and region semantics.', publicExport: true },
  { id: 'MediaPlaceholder', name: 'Media Placeholder', layer: 'component', status: 'stable', storyId: 'components-media-placeholder--playground', sourcePath: 'src/components/MediaPlaceholder/MediaPlaceholder.jsx', description: 'Fallback for unpublished or failed media.', publicExport: true },
  { id: 'ProfileGallery', name: 'Profile Gallery', layer: 'component', status: 'beta', storyId: 'components-profile-gallery--open', sourcePath: 'src/components/ProfileGallery/ProfileGallery.jsx', description: 'Focus-managed object media gallery.', publicExport: true },
  { id: 'FormField', name: 'Form Field', layer: 'component', status: 'stable', storyId: 'components-forms--textarea-and-select', sourcePath: 'src/components/UI/Forms/Forms.jsx', description: 'Label, control, hint and validation message contract.', publicExport: true },
  { id: 'Input', name: 'Input', layer: 'component', status: 'stable', storyId: 'components-forms--input-states', sourcePath: 'src/components/UI/Forms/Forms.jsx', description: 'Text input states including loading and validation.', publicExport: true },
  { id: 'ChoiceControls', name: 'Checkbox and Radio', layer: 'component', status: 'stable', storyId: 'components-forms--choice-controls', sourcePath: 'src/components/UI/Forms/Forms.jsx', description: 'Checkbox and radio controls with visible focus.', publicExport: true },
  { id: 'QuantityStepper', name: 'Quantity Stepper', layer: 'component', status: 'stable', storyId: 'components-forms--quantity-and-summary', sourcePath: 'src/components/UI/Forms/Forms.jsx', description: 'Bounded numeric control with announced output.', publicExport: true },
  { id: 'NavigationPrimitives', name: 'Navigation Primitives', layer: 'component', status: 'stable', storyId: 'components-content-and-states--navigation', sourcePath: 'src/components/UI/Core/Core.jsx', description: 'Breadcrumbs, back link and pagination composed with ghost Button actions and rounded interactive page states.', children: ['Button', 'Link'], publicExport: true },
  { id: 'AsyncStates', name: 'Async States', layer: 'component', status: 'stable', storyId: 'components-content-and-states--async-states', sourcePath: 'src/components/UI/Core/Core.jsx', description: 'Empty, loading and error feedback components.', publicExport: true },
  { id: 'Dialog', name: 'Dialog', layer: 'component', status: 'stable', storyId: 'components-content-and-states--accessible-dialog', sourcePath: 'src/components/UI/Core/Core.jsx', description: 'Focus-trapped accessible modal dialog composed with the shared Button action.', children: ['Button'], publicExport: true },
  { id: 'ListingCardFrame', name: 'Listing Card Frame', layer: 'component', status: 'stable', storyId: 'components-listing-cards--base', sourcePath: 'src/components/ListingCard/ListingCard.jsx', description: 'Shared geometry, media, focus and responsive behavior.', publicExport: true },
  { id: 'Rating', name: 'Rating', layer: 'primitive', status: 'stable', storyId: 'components-listing-cards--rating-component', sourcePath: 'src/components/ListingCard/ListingCard.jsx', description: 'Compact rating and supporting review count.', publicExport: true },
  { id: 'Price', name: 'Price', layer: 'primitive', status: 'stable', storyId: 'components-listing-cards--price-component', sourcePath: 'src/components/ListingCard/ListingCard.jsx', description: 'Formatted price and unit suffix.', publicExport: true },
  { id: 'DestinationCard', name: 'Destination Card Adapter', layer: 'component', status: 'beta', storyId: 'components-listing-cards--destination-variants', sourcePath: 'src/components/DestinationCard/DestinationCard.jsx', description: 'Migration adapter while catalog pages adopt explicit typed cards.', publicExport: true },
  { id: 'InstructorCard', name: 'Instructor Card', layer: 'component', status: 'stable', storyId: 'components-listing-cards--instructor-variants', sourcePath: 'src/components/InstructorCard/InstructorCard.jsx', description: 'Instructor-specific rating, experience and language data.', publicExport: true },
  { id: 'ActivityCard', name: 'Activity Card', layer: 'component', status: 'stable', storyId: 'components-listing-cards--typed-families', sourcePath: 'src/components/ListingCard/TypedListingCards.jsx', description: 'Activity-specific duration, rating and price data.', publicExport: true },
  { id: 'RentalCard', name: 'Rental Card', layer: 'component', status: 'beta', storyId: 'components-listing-cards--typed-families', sourcePath: 'src/components/ListingCard/TypedListingCards.jsx', description: 'Rental-specific equipment, availability and unit price.', publicExport: true },
  { id: 'TransferCard', name: 'Transfer Card', layer: 'component', status: 'beta', storyId: 'components-listing-cards--typed-families', sourcePath: 'src/components/ListingCard/TypedListingCards.jsx', description: 'Transfer-specific route, duration and vehicle data.', publicExport: true },
  { id: 'EditorialCard', name: 'Editorial Card', layer: 'component', status: 'stable', storyId: 'components-listing-cards--typed-families', sourcePath: 'src/components/ListingCard/TypedListingCards.jsx', description: 'Editorial category, publication and reading-time data.', publicExport: true },
  { id: 'CategoryTab', name: 'Category Tab', layer: 'component', status: 'stable', storyId: 'blocks-catalog-category-tabs--category-tab-component', sourcePath: 'src/components/CatalogCategoryTabs/CatalogCategoryTabs.jsx', description: 'Single category selection control.', publicExport: true },
  { id: 'FilterControl', name: 'Filter Control', layer: 'component', status: 'stable', storyId: 'blocks-catalog--filter-control-component', sourcePath: 'src/design-system/blocks/catalog/CatalogBlocks.jsx', description: 'Grouped multi-select catalog refinement popover with selected count, clear and disabled states.', publicExport: true },
  { id: 'ResultCount', name: 'Result Count', layer: 'component', status: 'stable', storyId: 'blocks-catalog--result-count-component', sourcePath: 'src/design-system/blocks/catalog/CatalogBlocks.jsx', description: 'Live result count feedback.', publicExport: true },
  { id: 'BenefitCard', name: 'Benefit Card', layer: 'component', status: 'stable', storyId: 'blocks-catalog--benefit-card-component', sourcePath: 'src/design-system/blocks/catalog/CatalogBlocks.jsx', description: 'Single catalog benefit.', publicExport: true },
  { id: 'BookingStep', name: 'Booking Step', layer: 'component', status: 'stable', storyId: 'blocks-catalog--booking-step-component', sourcePath: 'src/design-system/blocks/catalog/CatalogBlocks.jsx', description: 'Single numbered booking explanation.', publicExport: true },

  { id: 'SiteNavbar', name: 'Site Navbar', layer: 'block', status: 'stable', storyId: 'blocks-global-site-navbar--desktop-closed', sourcePath: 'src/components/SiteNavbar/SiteNavbar.jsx', description: 'Global navigation across responsive states.', publicExport: true },
  { id: 'SiteFooter', name: 'Site Footer', layer: 'block', status: 'stable', storyId: 'blocks-global-site-footer--desktop', sourcePath: 'src/components/SiteFooter/SiteFooter.jsx', description: 'Global footer navigation and project information.', publicExport: true },
  { id: 'SearchHero', name: 'Search Hero', layer: 'block', status: 'beta', storyId: 'blocks-marketing-search-hero--empty', sourcePath: 'src/design-system/blocks/marketing/MarketingBlocks.jsx', description: 'Approved marketing search entry point.', children: ['SectionHeading', 'Input', 'Button'], publicExport: true },
  { id: 'ContentPageHero', name: 'Content Page Hero', layer: 'block', status: 'stable', storyId: 'blocks-marketing-content-page-hero--without-media', sourcePath: 'src/design-system/blocks/marketing/MarketingBlocks.jsx', description: 'Shared top-level introduction for content pages with optional media, status and actions.', children: ['SectionHeading', 'Badge'], publicExport: true },
  { id: 'CategoryTabs', name: 'Category Tabs', layer: 'block', status: 'stable', storyId: 'blocks-catalog-category-tabs--default', sourcePath: 'src/components/CatalogCategoryTabs/CatalogCategoryTabs.jsx', description: 'Catalog category block.', children: ['CategoryTab'], publicExport: true },
  { id: 'FaqAccordion', name: 'FAQ Section', layer: 'block', status: 'stable', storyId: 'blocks-global-faq-section--first-item-open', sourcePath: 'src/components/FaqAccordion/FaqAccordion.jsx', description: 'Shared FAQ block for catalog, detail and content pages, composed with the common Accordion component.', children: ['SectionHeading', 'Accordion'], publicExport: true },
  { id: 'CatalogHero', name: 'Catalog Hero', layer: 'block', status: 'stable', storyId: 'blocks-catalog--catalog-hero-block', sourcePath: 'src/design-system/blocks/catalog/CatalogBlocks.jsx', description: 'Catalog-specific hero with confirmed centered or split-start alignment.', children: ['SectionHeading'], publicExport: true },
  { id: 'FilterToolbar', name: 'Filter Toolbar', layer: 'block', status: 'stable', storyId: 'blocks-catalog--filter-toolbar-block', sourcePath: 'src/design-system/blocks/catalog/CatalogBlocks.jsx', description: 'Wireframe-aligned selection heading, grouped refinements, live result count and clear actions.', children: ['SectionHeading', 'FilterControl', 'ResultCount'], publicExport: true },
  { id: 'ListingGrid', name: 'Listing Grid', layer: 'block', status: 'stable', storyId: 'blocks-catalog--listing-grid-ready', sourcePath: 'src/design-system/blocks/catalog/CatalogBlocks.jsx', description: 'Registered typed card grid with async states.', children: ['ActivityCard', 'InstructorCard', 'RentalCard', 'TransferCard', 'EditorialCard', 'AsyncStates'], publicExport: true },
  { id: 'BenefitsSection', name: 'Benefits Section', layer: 'block', status: 'stable', storyId: 'blocks-catalog--benefits', sourcePath: 'src/design-system/blocks/catalog/CatalogBlocks.jsx', description: 'Trust and benefit cards for catalogs.', children: ['SectionHeading', 'BenefitCard'], publicExport: true },
  { id: 'BookingSteps', name: 'Booking Steps', layer: 'block', status: 'stable', storyId: 'blocks-catalog--booking-steps-block', sourcePath: 'src/design-system/blocks/catalog/CatalogBlocks.jsx', description: 'Catalog-level booking explanation.', children: ['SectionHeading', 'BookingStep'], publicExport: true },
  { id: 'PromoArea', name: 'Promo Area', layer: 'block', status: 'stable', storyId: 'blocks-catalog-promo--split-promo', sourcePath: 'src/design-system/blocks/catalog/CatalogBlocks.jsx', description: 'Strict registry of split, rate, safety, selection and conditions promos.', children: ['Surface', 'Badge', 'Button'], publicExport: true },

  { id: 'ObjectHero', name: 'Object Hero', layer: 'block', status: 'stable', storyId: 'blocks-detail-object-hero--split', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Focused detail hero with a left-pinned back link, badges, display title, short description and optional side or lower media.', children: ['SectionHeading', 'Badge', 'MediaPlaceholder'], publicExport: true },
  { id: 'PrimaryFacts', name: 'Primary Facts', layer: 'block', status: 'stable', storyId: 'blocks-detail-primary-facts--default', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Primary object facts.', publicExport: true },
  { id: 'DescriptionSection', name: 'Description Section', layer: 'block', status: 'stable', storyId: 'blocks-detail-description-section--default', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Readable object description.', children: ['SectionHeading'], publicExport: true },
  { id: 'AdditionalDetails', name: 'Additional Details', layer: 'block', status: 'stable', storyId: 'blocks-detail-additional-details--default', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Structured secondary facts.', children: ['SectionHeading'], publicExport: true },
  { id: 'ReviewsSection', name: 'Reviews Section', layer: 'block', status: 'stable', storyId: 'blocks-detail-reviews-section--default', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Review summary and cards.', children: ['SectionHeading', 'Surface'], publicExport: true },
  { id: 'DetailBookingSteps', name: 'Detail Booking Steps', layer: 'block', status: 'stable', storyId: 'blocks-detail-booking-steps--default', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Object-level booking process.', children: ['SectionHeading', 'Badge'], publicExport: true },
  { id: 'RelatedListings', name: 'Related Listings', layer: 'block', status: 'stable', storyId: 'blocks-detail-related-listings--default', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Registered typed recommendations.', publicExport: true },
  { id: 'StickyBookingWidget', name: 'Sticky Booking Widget', layer: 'block', status: 'beta', storyId: 'blocks-detail-sticky-booking-widget--default', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Responsive sticky booking action.', children: ['Surface', 'Button'], publicExport: true },
  { id: 'RegisteredAdditionalSections', name: 'Registered Additional Sections', layer: 'block', status: 'internal', storyId: 'design-system-composition-registered-sections--allowed-registry', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Internal guard that rejects unregistered CMS detail sections.', publicExport: false },
  { id: 'CertificationsSection', name: 'Certifications Section', layer: 'block', status: 'stable', storyId: 'blocks-detail-specific-sections--certifications', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Registered certification content.', children: ['SectionHeading'], publicExport: true },
  { id: 'RouteProgram', name: 'Route Program', layer: 'block', status: 'stable', storyId: 'blocks-detail-specific-sections--route', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Registered route program content.', children: ['SectionHeading'], publicExport: true },
  { id: 'IncludedServices', name: 'Included Services', layer: 'block', status: 'stable', storyId: 'blocks-detail-specific-sections--included', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Registered included services.', children: ['SectionHeading'], publicExport: true },
  { id: 'EquipmentList', name: 'Equipment List', layer: 'block', status: 'stable', storyId: 'blocks-detail-specific-sections--equipment', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Registered equipment list.', children: ['SectionHeading'], publicExport: true },
  { id: 'SafetyRequirements', name: 'Safety Requirements', layer: 'block', status: 'stable', storyId: 'blocks-detail-specific-sections--safety', sourcePath: 'src/design-system/blocks/detail/DetailBlocks.jsx', description: 'Registered safety requirements.', children: ['SectionHeading'], publicExport: true },

  { id: 'ArticleHeader', name: 'Article Header', layer: 'block', status: 'stable', storyId: 'blocks-editorial-article-header--default', sourcePath: 'src/design-system/blocks/editorial/EditorialBlocks.jsx', description: 'Centered editorial display title, dek, back navigation and metadata.', children: ['SectionHeading', 'Badge'], publicExport: true },
  { id: 'ArticleMedia', name: 'Article Media', layer: 'block', status: 'stable', storyId: 'blocks-editorial-article-media--default', sourcePath: 'src/design-system/blocks/editorial/EditorialBlocks.jsx', description: 'Captioned editorial media.', children: ['MediaPlaceholder'], publicExport: true },
  { id: 'TableOfContents', name: 'Table of Contents', layer: 'block', status: 'stable', storyId: 'blocks-editorial-table-of-contents--default', sourcePath: 'src/design-system/blocks/editorial/EditorialBlocks.jsx', description: 'Stable heading-anchor navigation.', publicExport: true },
  { id: 'ArticleBody', name: 'Article Body', layer: 'block', status: 'stable', storyId: 'blocks-editorial-article-body--default', sourcePath: 'src/design-system/blocks/editorial/EditorialBlocks.jsx', description: 'Readable sanitized rich-text region.', publicExport: true },
  { id: 'ArticleNotice', name: 'Article Notice', layer: 'block', status: 'stable', storyId: 'blocks-editorial-article-notice--information', sourcePath: 'src/design-system/blocks/editorial/EditorialBlocks.jsx', description: 'Editorial callout using Notice.', publicExport: true },
  { id: 'Sources', name: 'Sources', layer: 'block', status: 'stable', storyId: 'blocks-editorial-sources--default', sourcePath: 'src/design-system/blocks/editorial/EditorialBlocks.jsx', description: 'Accessible external source list.', publicExport: true },
  { id: 'RelatedArticles', name: 'Related Articles', layer: 'block', status: 'stable', storyId: 'blocks-editorial-related-articles--default', sourcePath: 'src/design-system/blocks/editorial/EditorialBlocks.jsx', description: 'Editorial onward journey.', children: ['SectionHeading', 'EditorialCard'], publicExport: true },

  { id: 'CatalogDiscovery', name: 'Catalog Discovery', layer: 'pattern', status: 'stable', storyId: 'patterns-catalog-discovery--default', sourcePath: 'src/design-system/patterns/Patterns.jsx', description: 'Browse, filter, inspect results and paginate.', children: ['CategoryTabs', 'FilterToolbar', 'ListingGrid'], publicExport: true },
  { id: 'SearchAndFiltering', name: 'Search and Filtering', layer: 'pattern', status: 'stable', storyId: 'patterns-search-and-filtering--default', sourcePath: 'src/design-system/patterns/Patterns.jsx', description: 'Query and progressively narrow results.', children: ['FilterToolbar', 'ListingGrid'], publicExport: true },
  { id: 'BookingFlow', name: 'Booking Flow', layer: 'pattern', status: 'beta', storyId: 'patterns-booking-flow--default', sourcePath: 'src/design-system/patterns/Patterns.jsx', description: 'Multi-step progress, validation, summary and status.', publicExport: true },
  { id: 'SearchFlow', name: 'Search Flow', layer: 'pattern', status: 'stable', storyId: 'patterns-search-flow--default', sourcePath: 'src/design-system/patterns/Patterns.jsx', description: 'Search entry, feedback and results.', children: ['SearchHero', 'ListingGrid'], publicExport: true },
  { id: 'EmptyAndErrorResults', name: 'Empty and Error Results', layer: 'pattern', status: 'stable', storyId: 'patterns-empty-and-error-results--default', sourcePath: 'src/design-system/patterns/Patterns.jsx', description: 'Recovery behavior for async catalog states.', children: ['AsyncStates'], publicExport: true },
  { id: 'EditorialReading', name: 'Editorial Reading', layer: 'pattern', status: 'stable', storyId: 'patterns-editorial-reading--default', sourcePath: 'src/design-system/patterns/Patterns.jsx', description: 'Header, contents, body, sources and related reading.', children: ['ArticleHeader', 'TableOfContents', 'ArticleBody'], publicExport: true },

  { id: 'CatalogPageTemplate', name: 'Catalog Page Template', layer: 'template', status: 'stable', storyId: 'cms-templates-catalog-page-template--default', sourcePath: 'src/design-system/templates/CmsTemplates.jsx', description: 'Stable catalog CMS structure with named required and optional slots.', children: ['SiteNavbar', 'CatalogHero', 'CategoryTabs', 'FilterToolbar', 'ListingGrid', 'PromoArea', 'BenefitsSection', 'BookingSteps', 'FaqAccordion', 'SiteFooter'], publicExport: true },
  { id: 'ObjectDetailPageTemplate', name: 'Object Detail Page Template', layer: 'template', status: 'stable', storyId: 'cms-templates-object-detail-page-template--default', sourcePath: 'src/design-system/templates/CmsTemplates.jsx', description: 'Stable object detail CMS structure with registered additional sections and shared FAQ.', children: ['SiteNavbar', 'ObjectHero', 'PrimaryFacts', 'DescriptionSection', 'AdditionalDetails', 'RegisteredAdditionalSections', 'ReviewsSection', 'DetailBookingSteps', 'RelatedListings', 'FaqAccordion', 'StickyBookingWidget', 'SiteFooter'], publicExport: true },
  { id: 'EditorialArticleTemplate', name: 'Editorial Article Template', layer: 'template', status: 'beta', storyId: 'cms-templates-editorial-article-template--default', sourcePath: 'src/design-system/templates/CmsTemplates.jsx', description: 'Reusable long-form editorial structure.', children: ['SiteNavbar', 'ArticleHeader', 'ArticleMedia', 'TableOfContents', 'ArticleBody', 'Sources', 'RelatedArticles', 'SiteFooter'], publicExport: true },

  { id: 'Pill', name: 'Pill', layer: 'primitive', status: 'deprecated', storyId: 'deprecated-pill-compatibility--playground', sourcePath: 'src/components/UI/Pill/Pill.jsx', description: 'Compatibility adapter only.', publicExport: true, replacement: 'Badge or FilterChip', removalDate: '2027-01-31', legacyUsage: 'No production consumers; compatibility story only.', newUsageForbidden: true },
  { id: 'CompatibilityLayer', name: 'Compatibility Layer', layer: 'primitive', status: 'deprecated', storyId: 'deprecated-compatibility-layer--buttons', sourcePath: 'src/styles/SystemCompat.scss', description: 'Static prototype compatibility classes.', replacement: 'Public React design-system exports', removalDate: '2027-06-30', legacyUsage: 'Static prototypes under pages/', newUsageForbidden: true }
] as const satisfies readonly DesignSystemEntry[];

export const registryById = new Map<string, DesignSystemEntry>(DESIGN_SYSTEM_REGISTRY.map((entry) => [entry.id, entry]));

export function defineComposition(composition: CompositionParameter): CompositionParameter { return composition; }
