import { useState } from 'react';
import { BenefitCard, BenefitsSection, BookingStep, BookingSteps, Button, CatalogHero, FilterControl, FilterToolbar, ListingGrid, ResultCount } from '../design-system';
import { defineComposition } from '../design-system/architecture/registry';

const listings = [
  { slug: 'private-lesson', title: 'Private ski lesson', category: 'Lessons', rating: 4.9, reviews: 38, price: '240 GEL', priceSuffix: '2 hours', tags: ['Beginner', 'English'] },
  { slug: 'freeride-day', title: 'Freeride day', category: 'Adventure', rating: 4.8, reviews: 16, price: '520 GEL', priceSuffix: 'per group', tags: ['Advanced', '6 hours'] }
];

export default { title: 'Blocks/Catalog', tags: ['autodocs'], parameters: { controls: { disable: true } } };
const composition = (root) => ({ composition: defineComposition({ root }) });
export const CatalogHeroBlock = { name: 'Catalog Hero', parameters: composition('CatalogHero'), render: () => <CatalogHero kicker="Mountain experiences" title="Activities" description="Discover Gudauri beyond the piste with trusted local guides and clear itineraries." /> };
export const CatalogHeroSplitStart = { name: 'Catalog Hero / Split Start', parameters: composition('CatalogHero'), render: () => <CatalogHero align="start" kicker="Local knowledge" title="Articles" description="Practical guides for a smoother mountain trip — written with local experts and updated for the season." /> };
const languageOptions = [{ id: 'english', label: 'English' }, { id: 'russian', label: 'Russian' }, { id: 'georgian', label: 'Georgian' }];
const focusOptions = [{ id: 'first-lessons', label: 'First lessons' }, { id: 'technique', label: 'Technique' }, { id: 'freeride', label: 'Freeride' }];
function Toolbar() { const [selected, setSelected] = useState(['english']); const toggle = (id) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); const clear = (ids) => setSelected((current) => current.filter((id) => !ids.includes(id))); return <FilterToolbar title="Find the right fit" resultCount={18} resultLabel="instructors" controls={<><FilterControl id="story-language" label="Language" options={languageOptions} selectedValues={selected} onToggle={toggle} onClear={clear} /><FilterControl id="story-focus" label="Focus" options={focusOptions} selectedValues={selected} onToggle={toggle} onClear={clear} /></>} actions={<Button variant="link" onClick={() => setSelected([])}>Clear all</Button>} />; }
function Control() { const [selected, setSelected] = useState(['english']); return <FilterControl id="story-filter" label="Language" options={languageOptions} selectedValues={selected} onToggle={(id) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])} onClear={() => setSelected([])} />; }
export const FilterToolbarBlock = { name: 'Filter Toolbar', parameters: composition('FilterToolbar'), render: () => <div className="sb-canvas"><Toolbar /></div> };
export const FilterControlComponent = { name: 'Filter Control', parameters: composition('FilterControl'), render: () => <div className="sb-canvas"><Control /></div> };
export const FilterControlDisabled = { name: 'Filter Control / Disabled', parameters: composition('FilterControl'), render: () => <div className="sb-canvas"><FilterControl label="Language" options={languageOptions} disabled /></div> };
export const ResultCountComponent = { name: 'Result Count', parameters: composition('ResultCount'), render: () => <div className="sb-canvas"><ResultCount count={18} /></div> };
export const ListingGridReady = { name: 'Listing Grid / Ready', parameters: composition('ListingGrid'), render: () => <div className="sb-canvas"><ListingGrid items={listings} /></div> };
export const ListingGridStates = { name: 'Listing Grid / States', parameters: composition('ListingGrid'), render: () => <main className="sb-canvas sb-section"><ListingGrid state="loading" /><ListingGrid items={[]} emptyAction={<Button variant="secondary">Clear filters</Button>} /><ListingGrid state="error" onRetry={() => {}} /></main> };
export const Benefits = { name: 'Benefits Section', parameters: composition('BenefitsSection'), render: () => <BenefitsSection title="A calmer way to plan" description="Shared guarantees across every catalog type." items={[{ icon: '✓', title: 'Verified', description: 'Profiles and services are reviewed before publication.' }, { icon: '↗', title: 'Clear terms', description: 'Prices and conditions are visible before contact.' }, { icon: '●', title: 'Local support', description: 'A local operator helps if plans change.' }]} /> };
export const BenefitCardComponent = { name: 'Benefit Card', parameters: composition('BenefitCard'), render: () => <BenefitCard icon="✓" title="Verified" description="Reviewed before publication." /> };
export const BookingStepsBlock = { name: 'Booking Steps', parameters: composition('BookingSteps'), render: () => <BookingSteps items={[{ title: 'Choose', description: 'Compare registered offers.' }, { title: 'Request', description: 'Send dates and group details.' }, { title: 'Confirm', description: 'Receive final availability and terms.' }]} /> };
export const BookingStepComponent = { name: 'Booking Step', parameters: composition('BookingStep'), render: () => <BookingStep number={1} title="Choose" description="Compare registered offers." /> };
