import { useState } from 'react';
import { Checkbox, DateField, DateRangeCalendar, FormField, FormSummary, Input, QuantityStepper, Radio, Select, Textarea, TimeSlotPicker } from '../design-system';
import { defineComposition } from '../design-system/architecture/registry';

export default { title: 'Components/Forms', tags: ['autodocs'], parameters: { controls: { disable: true } } };
const composition = (root) => ({ composition: defineComposition({ root }) });

export const InputStates = { parameters: composition('Input'), render: () => <div className="sb-canvas sb-grid"><FormField label="Default" hint="Helpful supporting text"><Input placeholder="Your name" /></FormField><FormField label="Filled" success="Looks good"><Input defaultValue="Misha" /></FormField><FormField label="Error" error="Enter a valid email"><Input defaultValue="wrong@" /></FormField><FormField label="Disabled"><Input disabled value="Unavailable" readOnly /></FormField><FormField label="Loading"><Input loading value="Checking availability" readOnly /></FormField></div> };
export const TextareaAndSelect = { parameters: composition('FormField'), render: () => <div className="sb-canvas sb-grid"><FormField label="Notes"><Textarea placeholder="Goals, group, equipment" /></FormField><FormField label="Activity"><Select defaultValue="ski"><option value="ski">Ski</option><option value="snowboard">Snowboard</option></Select></FormField><FormField label="Date"><DateField /></FormField></div> };
export const ChoiceControls = { parameters: composition('ChoiceControls'), render: () => <div className="sb-canvas sb-section"><div className="sb-row"><Checkbox label="I need rental equipment" /><Checkbox label="Disabled" disabled /></div><div className="sb-row"><Radio name="pace" label="Relaxed" defaultChecked /><Radio name="pace" label="Active" /></div></div> };
function StepperExample({ variant = 'default', disabled = false }) { const [value, setValue] = useState(2); return <QuantityStepper variant={variant} label="participants" value={value} min={1} max={8} disabled={disabled} onChange={setValue} />; }
export const QuantityAndSummary = { parameters: composition('QuantityStepper'), render: () => <div className="sb-canvas sb-section"><div className="sb-row"><StepperExample /><div style={{ padding: 'var(--space-300)', borderRadius: 'var(--radius-md)', background: 'var(--surface-subtle)' }}><StepperExample variant="booking" /></div><StepperExample variant="booking" disabled /></div><FormSummary errors={[{ id: 'email', message: 'Enter a valid email', href: '#email' }, { id: 'date', message: 'Choose a date' }]} /></div> };
function DateRangeExample() { const [value, setValue] = useState({ start: '2026-12-14', end: '2026-12-17' }); return <div className="sb-canvas" style={{ maxWidth: 920 }}><DateRangeCalendar label="Preferred lesson dates" min="2026-12-01" value={value} onChange={setValue} /></div>; }
export const DateRange = { parameters: composition('DateRangeCalendar'), render: () => <DateRangeExample /> };
export const DateRangeDisabled = { parameters: composition('DateRangeCalendar'), render: () => <div className="sb-canvas" style={{ maxWidth: 920 }}><DateRangeCalendar label="Preferred lesson dates" min="2026-12-01" value={{ start: '2026-12-14', end: '2026-12-17' }} disabled /></div> };
function TimeSlotExample({ disabled = false }) { const [value, setValue] = useState({ '2026-12-14': ['morning'], '2026-12-15': ['morning', 'midday'], '2026-12-16': ['morning'] }); return <div className="sb-canvas" style={{ maxWidth: 760 }}><TimeSlotPicker disabled={disabled} days={[{ id: '2026-12-14', label: '14.12.26' }, { id: '2026-12-15', label: '15.12.26' }, { id: '2026-12-16', label: '16.12.26' }]} slots={[{ id: 'morning', label: '10:00–12:00', meta: 'slot 1 · 2h' }, { id: 'midday', label: '12:30–14:30', meta: 'slot 2 · 2h' }, { id: 'afternoon', label: '15:00–17:00', meta: 'slot 3 · 2h' }]} value={value} onChange={setValue} /></div>; }
export const TimeSlots = { parameters: composition('TimeSlotPicker'), render: () => <TimeSlotExample /> };
export const TimeSlotsDisabled = { parameters: composition('TimeSlotPicker'), render: () => <TimeSlotExample disabled /> };
